package com.eric.websome;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'steve_000' at '2016/8/24 下午 11:44' with Gradle 3.0
 *
 * @author steve_000, @date 2016/8/24 下午 11:44
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
