package com.eric.websome;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'steve_000' at '2016/8/24 下午 11:44' with Gradle 3.0
 *
 * @author steve_000, @date 2016/8/24 下午 11:44
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
